import {app,BrowserWindow,Tray,Menu,screen,ipcMain,shell,nativeImage} from 'electron';
import {spawn} from 'node:child_process';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import Store from 'electron-store';
const __dirname=path.dirname(fileURLToPath(import.meta.url)); const dev=process.env.VIPER_DEV==='1'; let win=null,tray=null;
const store=new Store({name:'viper-settings',defaults:{orbPosition:{x:null,y:null},orbSize:110,orbOpacity:1,glowIntensity:1,animationIntensity:1,alwaysOnTop:true,launchAtStartup:false,wakeWordEnabled:true,voiceEnabled:true,showStatusText:true,theme:'cyan'}});
function createWindow(){const p=store.get('orbPosition');const d=screen.getPrimaryDisplay().workArea;const s=320;win=new BrowserWindow({width:s,height:s,x:p?.x??d.width-s-40,y:p?.y??d.height-s-40,frame:false,transparent:true,hasShadow:false,resizable:false,fullscreenable:false,skipTaskbar:true,alwaysOnTop:true,focusable:false,backgroundColor:'#00000000',webPreferences:{preload:path.join(__dirname,'preload.js'),contextIsolation:true,nodeIntegration:false}});win.setAlwaysOnTop(store.get('alwaysOnTop'),'screen-saver');win.setVisibleOnAllWorkspaces(true,{visibleOnFullScreen:true});dev?win.loadURL('http://localhost:5173'):win.loadFile(path.join(__dirname,'../dist/index.html'));win.on('move',()=>{const [x,y]=win.getPosition();store.set('orbPosition',{x,y})});win.on('closed',()=>win=null)}
function trayMenu(){if(!tray)return;tray.setContextMenu(Menu.buildFromTemplate([{label:'Viper',enabled:false},{type:'separator'},{label:'Wake Word',type:'checkbox',checked:store.get('wakeWordEnabled'),click:i=>{store.set('wakeWordEnabled',i.checked);win?.webContents.send('settings:changed',{wakeWordEnabled:i.checked})}},{label:'Voice',type:'checkbox',checked:store.get('voiceEnabled'),click:i=>{store.set('voiceEnabled',i.checked);win?.webContents.send('settings:changed',{voiceEnabled:i.checked})}},{label:'Always on Top',type:'checkbox',checked:store.get('alwaysOnTop'),click:i=>{store.set('alwaysOnTop',i.checked);win?.setAlwaysOnTop(i.checked,'screen-saver')}},{label:'Launch at Startup',type:'checkbox',checked:store.get('launchAtStartup'),click:i=>{store.set('launchAtStartup',i.checked);app.setLoginItemSettings({openAtLogin:i.checked})}},{type:'separator'},{label:'Show Viper',click:()=>win?.show()},{label:'Quit Viper',click:()=>app.quit()}]))}
function createTray(){tray=new Tray(nativeImage.createEmpty());tray.setToolTip('Viper — Personal Intelligence System');trayMenu()}
const apps={chrome:'chrome.exe',edge:'msedge.exe',discord:'Discord.exe',spotify:'Spotify.exe',notepad:'notepad.exe',calculator:'calc.exe',vscode:'Code.exe'};
ipcMain.handle('viper:getSettings',()=>store.store);
ipcMain.handle('viper:setSetting',(_,k,v)=>{store.set(k,v);if(k==='alwaysOnTop')win?.setAlwaysOnTop(!!v,'screen-saver');trayMenu();return true});
ipcMain.handle('viper:executeFastCommand',(_,intent,entity)=>{if(intent==='open_app'&&apps[entity]){spawn(apps[entity],[],{detached:true,stdio:'ignore',windowsHide:true}).unref();return true}if(intent==='open_url'){shell.openExternal(entity);return true}if(intent==='open_folder'){const folder=entity==='downloads'?app.getPath('downloads'):app.getPath('documents');spawn('explorer.exe',[folder],{windowsHide:true});return true}if(intent==='lock_pc'){spawn('rundll32.exe',['user32.dll,LockWorkStation'],{windowsHide:true});return true}throw new Error('Unsupported fast command')});
ipcMain.handle('viper:minimizeToTray',()=>{win?.hide();return true});ipcMain.handle('viper:show',()=>{win?.show();return true});ipcMain.handle('viper:hide',()=>{win?.hide();return true});ipcMain.handle('viper:quit',()=>{app.quit();return true});
app.whenReady().then(()=>{createWindow();createTray();if(store.get('launchAtStartup'))app.setLoginItemSettings({openAtLogin:true})});app.on('window-all-closed',()=>{});
