import{useEffect,useRef,useState}from'react';import{useViperState}from'../../hooks/useViperState';import{STATE_CONFIG,type ViperSettings}from'../../core/types';import{viperEventBus}from'../../core/ViperEventBus';import{viperBackend}from'../../backend/ViperBackend';import{useAudioLevel}from'../../hooks/useAudioLevel';import'./ViperOrb.css';
export function ViperOrb({settings}:{settings:ViperSettings}){const state=useViperState(),cfg=STATE_CONFIG[state],mic=useAudioLevel('mic',state==='listening'),spk=useAudioLevel('speaker',state==='speaking'),level=state==='listening'?mic:spk,[listening,setListening]=useState(false),recorder=useRef<MediaRecorder|null>(null),stream=useRef<MediaStream|null>(null),chunks=useRef<Blob[]>([]);
useEffect(()=>()=>{stream.current?.getTracks().forEach(t=>t.stop())},[]);
const speak=async(text:string)=>{viperEventBus.emit('SPEECH_STARTED');try{if(window.viperNative?.tts){const src=await window.viperNative.tts(text);await new Promise<void>((resolve,reject)=>{const a=new Audio(src);a.onended=()=>resolve();a.onerror=()=>reject(new Error('Audio playback failed'));a.play().catch(reject)})}else{await new Promise<void>(resolve=>{const u=new SpeechSynthesisUtterance(text);u.rate=.98;u.onend=()=>resolve();speechSynthesis.speak(u)})}}catch{await new Promise<void>(resolve=>{const u=new SpeechSynthesisUtterance(text);u.onend=()=>resolve();speechSynthesis.speak(u)});viperEventBus.emit('SPEECH_COMPLETED');return}viperEventBus.emit('SPEECH_COMPLETED')};
const processText=async(text:string)=>{if(!text.trim())return;const result=await viperBackend.handleCommand(text);if(result.path==='local'){const ack=result.command?.acknowledgement||'Okay, boss.';await speak(ack)}else if(result.path==='ai'){try{const answer=await window.viperNative?.aiCommand(text);viperEventBus.emit('AI_TASK_COMPLETED',{text});await speak(answer||'I am ready, Mr. David.')}catch(e){viperEventBus.emit('ERROR',{error:e});await speak('I could not reach my AI services, boss. Check Viper Settings.')}}else await speak('I could not complete that command, boss.')};
const stopListening=()=>{if(!recorder.current)return;recorder.current.stop();setListening(false);viperEventBus.emit('SPEECH_COMPLETED')};
const startListening=async()=>{if(!settings.voiceEnabled||listening)return;if(!navigator.mediaDevices?.getUserMedia||typeof MediaRecorder==='undefined'){await speak('Microphone recording is not available on this Windows build, boss.');return}try{const s=await navigator.mediaDevices.getUserMedia({audio:{channelCount:1,echoCancellation:true,noiseSuppression:true,autoGainControl:true}});stream.current=s;chunks.current=[];const preferred=MediaRecorder.isTypeSupported('audio/webm;codecs=opus')?'audio/webm;codecs=opus':'audio/webm';const r=new MediaRecorder(s,{mimeType:preferred});recorder.current=r;r.ondataavailable=e=>{if(e.data.size)chunks.current.push(e.data)};r.onstop=async()=>{try{const blob=new Blob(chunks.current,{type:'audio/webm'});s.getTracks().forEach(t=>t.stop());stream.current=null;recorder.current=null;if(blob.size<1000){await speak('I did not hear anything, boss.');return}viperEventBus.emit('AI_TASK_STARTED',{text:'transcription'});const buffer=await blob.arrayBuffer();const text=await window.viperNative?.transcribe(new Uint8Array(buffer));if(text?.trim())await processText(text);else await speak('I did not catch that, boss.')}catch(e){viperEventBus.emit('ERROR',{error:e});await speak('Voice transcription failed, boss. Check your OpenAI key in Viper Settings.')}};r.onerror=()=>{setListening(false);viperEventBus.emit('ERROR',{error:'Microphone recording failed'})};r.start();setListening(true);viperEventBus.emit('WAKE_WORD_DETECTED')}catch(e){viperEventBus.emit('ERROR',{error:e});await speak('I cannot access the microphone, boss. Please allow microphone access for Viper.')}};
const toggleListening=()=>{if(listening)stopListening();else void startListening()};
return <div className={`viper-orb ${state}`} style={{'--size':`${settings.orbSize}px`,'--level':level,'--glow':cfg.glowIntensity*settings.glowIntensity,'--opacity':settings.orbOpacity} as React.CSSProperties} onDoubleClick={e=>{if(!(e.target as HTMLElement).closest('.core'))void window.viperNative?.openSettings()}}><div className="rings"><i/><i/><i/></div><div className="particles">{Array.from({length:16},(_,i)=><b key={i} style={{'--i':i} as React.CSSProperties}/>)}</div><button className="core" onClick={toggleListening} aria-label={listening?'Stop listening':'Talk to Viper'}><span>V</span></button>{settings.showStatusText&&cfg.statusLabel&&<small>{cfg.statusLabel}</small>}</div>}
